version: '3'

services:
  influxdb:
    image: docker.io/influxdb:1.7
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb:/var/lib/influxdb
  app:
    build: ./app
    command: /bin/bash -c "while true ; do /usr/local/bin/python /app/main.py ; sleep 30 ; done"
    depends_on:
      - "influxdb"
  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/data:/var/lib/grafana
    depends_on:
      - "influxdb"